server:
  port: 9092
  #缓慢的HTTP拒绝服务攻击漏洞解决办法
  tomcat:
    max-connections: 2000
    connection-timeout: 30000
  #Cookie没有HttpOnly安全标志设置漏洞解决办法
  servlet:
    session:
      cookie:
        http-only: true
spring:
  main:
    # 为了处理swagger兼容问题带来的bean冲突
    allow-bean-definition-overriding: true
  messages:
    encoding: UTF-8
    basename: messages/message
  jackson:
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd HH:mm:ss
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: Asia/Shanghai
    # 常规默认,枚举类SerializationFeature中的枚举属性为key，值为boolean设置jackson序列化特性,具体key请看SerializationFeature源码
    serialization:
      WRITE_ENUMS_USING_TO_STRING: true
      #      WRITE_DATES_AS_TIMESTAMPS: true # 返回的java.util.date转换成timestamp
      FAIL_ON_EMPTY_BEANS: true # 对象为空时是否报错，默认true
    deserialization:
      # 常用,json中含pojo不存在属性时是否失败报错,默认true
      FAIL_ON_UNKNOWN_PROPERTIES: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

